spring:
   profiles: local
   application:
      name: demo-cliente
   server:
      port: 8888
      contextPath: /demo-cliente
   jpa:
       database-platform: org.hibernate.dialect.SQLServer2012Dialect
       show-sql: true
       hibernate:
          ddl-auto: false
          dialect: org.hibernate.dialect.SQLServer2012Dialect
   datasource:
       maxActive: 3
       testWhileIdle: true
       timeBetweenEvictionRunsMillis: 3600000
       validationQuery: SELECT 1
       url: jdbc:sqlserver://localhost;databaseName=test_microservicios
       username: sa
       password: Admin2017
       driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
